### ISSUE TITLE
MongoDB database mismatch

### ISSUE THREAD

**Issue by clementmouret** [Swaven/node-db-connector#4]
In case of single MongoDB configuration name as string or array with one element **that doesn't match the authentication database** in connection string, the target database name is ignored and the authentication db is used by default.

Following configuration reference db1 and not db2:
```
  -
    name: db2
    connectionString: mongodb://xxx:yyy@myserver/db1
  -
    name:
      - db2
    connectionString: mongodb://xxx:yyy@myserver/db1
```
